# Generated by Django 4.2.14 on 2024-09-11 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_servicer_otp'),
        ('services', '0009_servicebooking_stripe_session_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_subscriptionpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('stars', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('review_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('servicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.servicer')),
            ],
        ),
    ]
