# Generated by Django 4.2.14 on 2024-07-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicer.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('event_types', models.ManyToManyField(related_name='service_types', through='servicer.EventServiceType', to='servicer.eventtype')),
            ],
        ),
        migrations.AddField(
            model_name='eventservicetype',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicer.servicetype'),
        ),
        migrations.AlterUniqueTogether(
            name='eventservicetype',
            unique_together={('event_type', 'service_type')},
        ),
    ]
