# Generated by Django 4.2.14 on 2024-08-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0002_servicer_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(choices=[('Kasaragod', 'Kasaragod'), ('Kannur', 'Kannur'), ('Wayanad', 'Wayanad'), ('Kozhikode', 'Kozhikode'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Malappuram', 'Malappuram'), ('Kottayam', 'Kottayam'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta')], max_length=50)),
                ('service_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('vehicle_washing', 'Vehicle Washing'), ('specific', 'Specific Cleaning')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employees_required', models.PositiveIntegerField(default=1)),
                ('duration', models.DurationField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.servicer')),
            ],
        ),
    ]
