# Generated by Django 4.2.14 on 2024-08-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
