# Generated by Django 4.2.14 on 2024-08-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='servicer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='servicer_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
