# Generated by Django 4.2.14 on 2024-08-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_servicer_name_service_servicer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
    ]
