# Generated by Django 4.2.14 on 2024-08-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='longitude',
        ),
    ]
