# Generated by Django 4.2.14 on 2024-08-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_servicebooking_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='approval_by_servicer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Approved', 'Approved'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
