# Generated by Django 4.2.14 on 2024-08-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_servicebooking_approval_by_servicer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
