# Generated by Django 4.2.14 on 2024-10-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_servicer',
            field=models.BooleanField(default=False),
        ),
    ]
